# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ef2a019817102ef9fee1ac641412ed88b2eef02c3d898f7d568db58d53463a039440bd701975580ea8af568b91c79a5b0a193881a56addaac18080b78776c8

test:
  secret_key_base: a704bb06d81cecf901bba24476b32ca43c140fd292d34d76f4bde382cc4a9de1c61f35227dc9cc3d7aba85d80fe0f98748adfd00dd77e558556e6aa5b674e0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
